version: '3.9'
services:
  python-app:
    build:
      context: .
      dockerfile: docker/py.dockerfile
    volumes:
      - type: bind
        source: /mnt/voldck/py/workdir
        target: /usr/src/app
    container_name: python-app
    networks:
      - ctnet

  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: /mnt/voldck/py/workdir
        target: /home/jovyan/work
    container_name: jupyter-notebook
    networks:
      - ctnet
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - type: bind
        source: /mnt/voldck/pg/
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: postgres-db
    networks:
      - ctnet
  apache:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    volumes:
      - type: bind
        source: /mnt/voldck/web/
        target: /usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    container_name: apache-server
    networks:
      - ctnet

networks:
  ctnet:
    driver: bridge