services:
  # python-app:
  #   build:
  #     context: .
  #     dockerfile: docker/py.dockerfile
  #   volumes:
  #     - workdir-app:/app
  #   container_name: python-app
  #   networks:
  #     - ctnet

  python-app:
    build:
      context: .
      dockerfile: docker/py.dockerfile
    ports:
      - "8889:8888"
    volumes:
      - workdir-app:/home/jovyan/work:rw
    container_name: jupyter-notebook
    networks:
      - ctnet
    command: start-notebook.py --NotebookApp.token='my-token'
  postgres:
    image: postgres:latest
    env_file:
      - ./docker/.env
    volumes:
      - type: bind
        source: /mnt/voldck/pg/
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: postgres-db
    networks:
      - ctnet
  apache:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    volumes:
        - www:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    container_name: apache-server
    networks:
      - ctnet

volumes:
  workdir-app:
  www:

networks:
  ctnet:
    driver: bridge