services:
  # python-app:
  #   build:
  #     context: .
  #     dockerfile: docker/py.dockerfile
  #   volumes:
  #     - workdir-app:/app
  #   container_name: python-app
  #   networks:
  #     - ctnet

  python-app:
    build:
      context: .
      dockerfile: docker/py.dockerfile
    ports:
      - "8889:8888"
    volumes:
      - workdir-app:/home/jovyan/work:rw
    container_name: jupyter-notebook
    networks:
      - ctnet
    command: start-notebook.py --NotebookApp.token='my-token'
  db:
    image: mysql
    env_file:
      - ./docker/.env
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment: 
      MYSQL_DATABASE: dbmusicadata
      MYSQL_USER: sa
      MYSQL_PASSWORD: ffti8p68
      MYSQL_ROOT_PASSWORD: managerffti8p68
    networks: 
      - ctnet
  apache:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    volumes:
        - www:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    container_name: apache-server
    networks:
      - ctnet

volumes:
  workdir-app:
  www:
  mysql:

networks:
  ctnet:
    driver: bridge